name: Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: k8s

    steps:
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"


    - id: slack_message
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # The following message update step does not accept a channel name.
        # Setting a channel ID here for consistency is highly recommended.
        channel-id: "C0468FV9M63"
        payload: |
          {
            "text": "Build Start (Server)",
            "attachments": [
              {
                "pretext": "Deployment started",
                "color": "dbab09",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "In Progress"
                  },
                  {
                    "title": "URL",
                    "short": true,
                    "value": "${{ github.server_url }}/${{ github.repository }}"
                  },
                  {
                    "title": "Ref",
                    "short": true,
                    "value": "${{ github.ref }}"
                  },
                  {
                    "title": "Sha",
                    "short": true,
                    "value": "${{ github.sha }}"
                  },
                  {
                    "title": "Commits",
                    "value": "${{ github.event.push.commits.*.message }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        
        
    - uses: actions/checkout@v3


    - name: Set up Docker Context for Buildx
      id: buildx-context
      run: |
        docker context create builders


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        endpoint: builders
        config-inline: |
          [registry."registry.container-registry.svc.cluster.local:5000"]
            http = true

    # Migrate
    - uses: actions/setup-node@v3
      with:
        node-version: 16


    # Create & Push docker image
    - name: Build and push Docker Image
      uses: docker/build-push-action@v3
      with:
        push: true
        context: .
        file: infra/docker/Dockerfile
        tags: |
          registry.container-registry.svc.cluster.local:5000/server:${{ steps.slug.outputs.sha7 }}
        cache-from: type=registry,ref=registry.container-registry.svc.cluster.local:5000/server:buildcache
        cache-to: type=registry,ref=registry.container-registry.svc.cluster.local:5000/server:buildcache,mode=max

    # Deploy K8s
    - name: Deploy
      run: |
        helm upgrade logic-server ./infra/helm/logic-server --set tag=${{ steps.slug.outputs.sha7 }} --namespace ajou-coding-hub --install



